[build]
  # Override the build command to bypass npm audit with --no-audit flag
  command = "export NPM_CONFIG_AUDIT=false && NODE_ENV=production npm run build && cd netlify/functions && npm install --no-audit --no-fund"
  publish = "dist/client"
  functions = "netlify/functions"
  
[build.environment]
  # Configure Netlify build environment to ignore vulnerabilities
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-audit --no-fund --production"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200