[build]
  # Use simplified build approach to bypass dependency issues
  command = "node netlify-simplified-build.cjs"
  publish = "dist/client"

# Handle client-side routing - this ensures all routes are directed to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Disable processing to preserve our build output
[build.processing]
  skip_processing = true

# Make sure the site has time to build
[build.environment]
  NODE_VERSION = "18"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_ENV = "production"
  # Set build logging to verbose
  DEBUG = "netlify:build:*"
