[build]
  command = "node netlify-build-fix.cjs && npm run build && node netlify-post-build.cjs"
  publish = "dist/client"
  environment = { NODE_VERSION = "18" }

# Handle client-side routing - this ensures all routes are directed to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Disable processing to preserve our build output
[build.processing]
  skip_processing = true

# Make sure the site has time to build
[build.environment]
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--legacy-peer-deps"