[build]
  command = "./prepare-netlify-deploy.sh && ./node_modules/.bin/vite build --config vite.netlify.config.js && node netlify-build-fix.js"
  publish = "dist/public"

# Add special handling for files that are dynamically imported
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable link checking plugin since it's causing build failures
[build.processing]
  skip_processing = true

[[plugins]]
  package = "netlify-plugin-checklinks"
  [plugins.inputs]
    skipPatterns = ['/mood-hub', '/direct-mood-selector.html']