[build]
  # Comprehensive build command with explicit dependency installation 
  command = """
    export NPM_CONFIG_AUDIT=false && 
    npm install --no-audit --no-fund --production serverless-http cors express body-parser express-session memorystore && 
    NODE_ENV=production npm run build && 
    cd netlify/functions && 
    npm install --no-audit --no-fund --production
  """
  publish = "dist/client"
  functions = "netlify/functions"
  
[build.environment]
  # Configure Netlify build environment to ignore vulnerabilities
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-audit --no-fund --production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"

[functions]
  node_bundler = "esbuild"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200