import { Challenge } from '@shared/schema';

// Create a list of mental health and wellness challenges
export const predefinedChallenges: Partial<Challenge>[] = [
  {
    title: "Morning Mindfulness Meditation",
    description: "Start each day with a 5-minute meditation focusing on your breath. Find a quiet spot, sit comfortably, and focus on your inhales and exhales. Notice thoughts without judgment and gently return to your breath when distracted.",
    category: "mindfulness",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 7,
    tags: "meditation,mindfulness,morning routine",
  },
  {
    title: "Digital Detox Evening",
    description: "Turn off all electronic devices 1 hour before bedtime for better sleep quality. Instead, engage in relaxing activities like reading, journaling, or gentle stretching to prepare your mind and body for rest.",
    category: "sleep",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 5,
    tags: "sleep,digital wellness,evening routine",
  },
  {
    title: "Gratitude Journaling Challenge",
    description: "Write down three things you're grateful for each day. Be specific and reflect on why these things bring you joy or appreciation. Over time, you'll train your brain to notice the positive aspects of your life more readily.",
    category: "gratitude",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 14,
    tags: "journaling,gratitude,positivity",
  },
  {
    title: "Nature Connection Walk",
    description: "Take a 20-minute walk in nature, paying attention to the sights, sounds, smells, and textures around you. Leave your phone behind or put it on silent to fully immerse yourself in the natural environment.",
    category: "physical activity",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 3,
    tags: "nature,walking,mindfulness",
  },
  {
    title: "Random Acts of Kindness",
    description: "Perform one small, unexpected act of kindness each day. It could be as simple as leaving an encouraging note for someone, complimenting a stranger, or helping a neighbor with a task. Notice how giving affects your own mood.",
    category: "social connection",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 7,
    tags: "kindness,community,positivity",
  },
  {
    title: "Emotional Awareness Journal",
    description: "Set aside 10 minutes daily to identify and write about your emotions. Name the emotions you've experienced, what triggered them, and how you responded. This practice builds emotional intelligence and self-understanding.",
    category: "emotional intelligence",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 10,
    tags: "journaling,emotions,self-awareness",
  },
  {
    title: "Worry Time Boundary",
    description: "Schedule a specific 15-minute 'worry time' each day. Outside this time, when worries arise, note them down to address during your designated worry time. This helps contain anxiety and prevents it from dominating your day.",
    category: "stress reduction",
    difficulty: "hard",
    tokenReward: 1,
    targetValue: 7,
    tags: "anxiety,stress management,boundaries",
  },
  {
    title: "Hydration Habit Builder",
    description: "Drink 8 glasses of water throughout the day. Set up reminders or use a marked water bottle to track your intake. Proper hydration improves mood, cognitive function, and overall physical wellbeing.",
    category: "nutrition",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 14,
    tags: "hydration,nutrition,health",
  },
  {
    title: "Creative Expression Time",
    description: "Spend 30 minutes engaging in a creative activity without judgment or expectations. This could be drawing, writing, playing music, dancing, or any form of artistic expression that allows you to enter a flow state.",
    category: "creativity",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 5,
    tags: "creativity,self-expression,flow",
  },
  {
    title: "Deep Breathing Breaks",
    description: "Take three 2-minute breaks throughout your day to practice deep breathing. Inhale slowly for 4 counts, hold for 2, and exhale for 6 counts. This activates your parasympathetic nervous system and reduces stress hormones.",
    category: "stress reduction",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 10,
    tags: "breathing,stress relief,quick practice",
  },
  {
    title: "Social Media Limitation",
    description: "Limit social media use to 30 minutes per day. Use app timers to help enforce this boundary. Notice how you feel with reduced scrolling time and how you use the reclaimed time in your day.",
    category: "digital wellbeing",
    difficulty: "hard",
    tokenReward: 1,
    targetValue: 7,
    tags: "digital wellness,boundaries,focus",
  },
  {
    title: "Compliment Mirror Exercise",
    description: "Look at yourself in the mirror each morning and give yourself three genuine compliments—about your character, accomplishments, or qualities, not just appearance. This builds self-compassion and positive self-talk habits.",
    category: "personal growth",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 14,
    tags: "self-compassion,positive psychology,morning routine",
  },
  {
    title: "Bedtime Routine Establishment",
    description: "Create and follow a consistent 15-minute bedtime routine to signal to your body it's time for sleep. This might include gentle stretching, reading, or a skincare routine—performed in the same order each night.",
    category: "sleep",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 10,
    tags: "sleep,evening routine,habits",
  },
  {
    title: "Mindful Eating Practice",
    description: "Eat one meal per day without distractions (no phones, TV, or reading). Pay full attention to the flavors, textures, and your body's hunger and fullness signals. Chew slowly and pause between bites to enhance digestion and enjoyment.",
    category: "nutrition",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 7,
    tags: "mindful eating,nutrition,presence",
  },
  {
    title: "Strength Affirmation Practice",
    description: "Create three personal affirmations that acknowledge your strengths and resilience. Repeat these affirmations aloud each morning, focusing on believing and embodying these truths about yourself.",
    category: "personal growth",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 21,
    tags: "affirmations,self-esteem,morning routine",
  },
  {
    title: "Technology-Free Meal Challenge",
    description: "Have at least one meal per day without any electronic devices present. Focus on the food and any companions, or simply enjoy your own company. Notice how this changes your perception of the meal and your satisfaction afterwards.",
    category: "digital wellbeing",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 7,
    tags: "digital wellness,mindful eating,presence",
  },
  {
    title: "Intentional Connection Call",
    description: "Schedule a 15+ minute phone call with a friend or family member you care about but don't often connect with. Ask meaningful questions and practice active listening instead of just talking about yourself or discussing logistics.",
    category: "social connection",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 3,
    tags: "relationships,communication,connection",
  },
  {
    title: "Body Scan Relaxation Practice",
    description: "Before sleep, lie on your back and mentally scan through your body from toes to head, consciously relaxing each muscle group. Notice areas of tension without judgment and imagine breathing warmth and relaxation into those areas.",
    category: "stress reduction",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 5,
    tags: "relaxation,sleep,body awareness",
  },
  {
    title: "New Learning Daily Practice",
    description: "Spend 15 minutes each day learning something new—read an educational article, watch a tutorial video, or practice a new skill. Learning keeps your brain active and provides a sense of growth and accomplishment.",
    category: "learning",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 14,
    tags: "learning,growth,brain health",
  },
  {
    title: "Environmental Decluttering Session",
    description: "Spend 15 minutes each day decluttering one small area of your living or working space. A clearer physical environment helps create mental clarity and reduces the subconscious stress of visual chaos.",
    category: "environmental",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 7,
    tags: "decluttering,organization,environment",
  },
  {
    title: "Boundary Setting Practice",
    description: "Identify one boundary you need to establish or reinforce in your work or personal life. Practice communicating this boundary clearly and holding firm when tested. Notice how proper boundaries protect your energy and wellbeing.",
    category: "personal growth",
    difficulty: "hard",
    tokenReward: 1,
    targetValue: 3,
    tags: "boundaries,communication,self-care",
  },
  {
    title: "Nature Immersion Therapy",
    description: "Spend 30+ minutes fully immersed in a natural setting (forest, beach, park) without technological interruptions. Research shows that time in nature reduces cortisol levels and improves mood and cognitive function.",
    category: "environmental",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 4,
    tags: "nature,stress relief,outdoor therapy",
  },
  {
    title: "Worry-to-Action Transformation",
    description: "When you catch yourself worrying, write down the concern, then immediately write one small, concrete action you could take to address it. Take that action if possible. This converts anxious energy into productive problem-solving.",
    category: "stress reduction",
    difficulty: "hard",
    tokenReward: 1,
    targetValue: 10,
    tags: "anxiety,action,problem-solving",
  },
  {
    title: "Digital Communication Audit",
    description: "Review your email subscriptions, social media accounts, and messaging apps. Unsubscribe, unfollow, or mute sources that don't add value to your life or that trigger negative emotions. Streamline your digital inputs for peace of mind.",
    category: "digital wellbeing",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 1,
    tags: "digital minimalism,focus,mental clarity",
  },
  {
    title: "Financial Wellbeing Check-In",
    description: "Spend 20 minutes reviewing your recent expenses and budget. Identify one area where you could make a positive adjustment. Financial stress significantly impacts mental health, and regular money management reduces financial anxiety.",
    category: "financial wellbeing",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 4,
    tags: "financial wellness,stress reduction,planning",
  },
  {
    title: "Emotional Vocabulary Expansion",
    description: "When identifying your emotions, challenge yourself to use specific terms beyond 'good,' 'bad,' 'fine,' or 'stressed.' Learn new emotion words and notice the nuances between similar feelings like disappointment versus discouragement.",
    category: "emotional intelligence",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 7,
    tags: "emotions,vocabulary,self-awareness",
  },
  {
    title: "Habit Stacking Integration",
    description: "Choose one small wellbeing practice (like a minute of deep breathing) and attach it to something you already do daily (like brushing teeth). This 'habit stacking' approach makes it easier to establish new positive routines.",
    category: "productivity",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 14,
    tags: "habits,routine building,consistency",
  },
  {
    title: "Intentional Joy Scheduling",
    description: "Plan and schedule one activity each day that brings you genuine joy or pleasure. Treat this appointment as non-negotiable, even if it's just for 10-15 minutes. Prioritizing positive emotions improves resilience and life satisfaction.",
    category: "personal growth",
    difficulty: "easy",
    tokenReward: 1,
    targetValue: 7,
    tags: "joy,scheduling,positive psychology",
  },
  {
    title: "Values-Aligned Decision Making",
    description: "Before making any significant decision today, pause and ask: 'Does this choice align with my core values?' Identify your top 3-5 values if you haven't already, and use them as a compass for daily choices.",
    category: "personal growth",
    difficulty: "hard",
    tokenReward: 1,
    targetValue: 5,
    tags: "values,decision making,authenticity",
  },
  {
    title: "Loving-Kindness Meditation",
    description: "Practice a 10-minute loving-kindness meditation where you mentally send good wishes to yourself, someone you love, someone neutral in your life, someone difficult, and all beings. This practice increases compassion and positive emotions.",
    category: "mindfulness",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 5,
    tags: "meditation,compassion,positive emotions",
  },
  {
    title: "Work-Break Balance Technique",
    description: "Use the Pomodoro Technique or a similar time-blocking method to work in focused intervals (25-50 minutes) followed by intentional 5-10 minute breaks. During breaks, physically move away from your work area and rest your eyes and mind.",
    category: "work-life balance",
    difficulty: "moderate",
    tokenReward: 1,
    targetValue: 10,
    tags: "productivity,focus,breaks",
  },
];

// Export a function to get a random selection of challenges
export function getRandomChallenges(count: number): Partial<Challenge>[] {
  const shuffled = [...predefinedChallenges].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}