[build]
  # Comprehensive build command with explicit dependency installation and custom installation script
  command = """
    export NPM_CONFIG_AUDIT=false &&
    npm install --no-audit --no-fund &&
    node ensure-assets.cjs &&
    node netlify-build-fix.cjs &&
    npm install --no-audit --no-fund --production serverless-http cors express body-parser express-session memorystore uuid &&
    npm install --no-audit --no-fund vite esbuild @vitejs/plugin-react typescript react-scripts &&
    NODE_ENV=production npm run build && 
    # Try to run the ES module version first, fall back to CommonJS if that fails
    node netlify/functions/install.mjs || node netlify/functions/install.cjs
  """
  publish = "dist/public"
  functions = "netlify/functions"
  
[build.environment]
  # Configure Netlify build environment to ignore vulnerabilities
  NODE_OPTIONS = "--max-old-space-size=4096"
  NETLIFY_USE_YARN = "false"
  NPM_FLAGS = "--no-audit --no-fund --production"
  NPM_CONFIG_LEGACY_PEER_DEPS = "true"
  NODE_VERSION = "18.18.0"
  USE_IDIOMATIC_VERSION_FILES = "true"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express", "serverless-http", "cors", "body-parser", "express-session", "memorystore", "uuid"]
  
  # Define environment variables for functions
  [functions.environment]
    NODE_ENV = "production"
    # Force path handling in JS to use current working directory
    FUNCTIONS_PATH_MODE = "cwd"
    # Explicitly tell Netlify functions to use ES modules
    ES_MODULE_SUPPORT = "true"

[[plugins]]
package = "@netlify/plugin-functions-install-core"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

# Admin routes
[[redirects]]
  from = "/admin/*"
  to = "/index.html"
  status = 200
  force = true

# Specific routes that need to be handled by the SPA
[[redirects]]
  from = "/auth"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/profile/*"
  to = "/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/emotions/*"
  to = "/index.html"
  status = 200
  force = true

# Default catch-all route for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200