[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/netlify-debug"
  to = "/.netlify/functions/netlify-debug"
  status = 200
  force = true

[[redirects]]
  from = "/api/healthcheck"
  to = "/.netlify/functions/api/healthcheck"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200